# values for the addon
addons:
  external_secrets:
    values:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: '' # override with empty string because we are using pod identity not IRSA
  karpenter:
    values:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: '' # override with empty string because we are using pod identity not IRSA
  aws_load_balancer_controller:
    values:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: '' # override with empty string because we are using pod identity not IRSA
